In [8]:
import pandas as pd

df = pd.read_csv("../data/spam.csv", encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [9]:
df = df[["v1", "v2"]]
df.columns = ["label", "message"]
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
print(df.shape)
df.info()
print(df.isnull().sum())
print(df.duplicated().sum())

(5572, 2)
<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   str
 1   message  5572 non-null   str
dtypes: str(2)
memory usage: 541.4 KB
label      0
message    0
dtype: int64
403

In [11]:
df = df.drop_duplicates()
print(df.shape)

(5169, 2)

In [12]:
print(df["label"].value_counts())
print(df["label"].value_counts(normalize=True) * 100)

label
ham     4516
spam     653
Name: count, dtype: int64
label
ham     87.366996
spam    12.633004
Name: proportion, dtype: float64

In [13]:
print("SPAM examples:")
for msg in df[df["label"] == "spam"]["message"].head(3):
    print("-", msg)

print("\nHAM examples:")
for msg in df[df["label"] == "ham"]["message"].head(3):
    print("-", msg)

SPAM examples:
- Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
- FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv
- WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.

HAM examples:
- Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
- Ok lar... Joking wif u oni...
- U dun say so early hor... U c already then say...

In [14]:
df["length"] = df["message"].apply(len)
df.groupby("label")["length"].describe()

        count        mean        std   min    25%    50%    75%    max
label
ham    4516.0   70.459256  56.358207   2.0   34.0   52.0   90.0  910.0
spam    653.0  137.891271  30.137753  13.0  132.0  149.0  157.0  224.0